### ISSUE TITLE
Make it in Typescript

### ISSUE THREAD

**Issue by AsteroidusTv** [Vital-Vuillaume/Project-Booklet#1]
Javascript is a lousy language for lousy developers (allow me the language) so do it in typescript it's the same, as worst asking a chatgpt to convert JavaScript to Typescript. Like this you will be able to make clean code without errors and no longer be able to do:

2 + "2" = 22
2 - "2" = 0

Or :

0 = []
0 = "0"
"0" != []

Thank you in advance for your understanding
and all my respect to you (only if you do in typescript (Or in rust (YOU MUST LEARN RUST)))

**Comment by Vital-Vuillaume** [comment]
No for small projects like that no need to get confused to do Ts.

But of course Ts > Js

On bigger and more serious projects I will do 100% of the Ts.

**Comment by AsteroidusTv** [comment]
This project is an Serious, big and Interesant project you must do it in Typescript

**Comment by AsteroidusTv** [comment]
And Its allways better (For small project too) to use the best technologies (Like rust)

**Comment by Vital-Vuillaume** [comment]
Maybe in the future if the site becomes too heavy.

**Comment by AsteroidusTv** [comment]
Ok..... bro
